name: bondtime
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  flutter_svg: ^2.0.7
  cupertino_icons: ^1.0.8
  url_launcher: ^6.0.20
  provider: ^6.1.0
  logger: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/bondtime-logo.svg
    - assets/icons/arrow-back.svg
    - assets/icons/online-patients.svg
    - assets/icons/home-visits.svg
    - assets/icons/years-experience.svg
    - assets/icons/locations-to-meat.svg
    - assets/icons/sms.svg
    - assets/icons/tel.svg

    - assets/images/doctor.jpg
    - assets/images/doctor2.jpg

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/InterTight-Regular.ttf
        - asset: assets/fonts/InterTight-Bold.ttf
          weight: 700
