name: bondtime_activity
description: A new Flutter project for BondTime's Activity Screen.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.7
  flutter_tts: ^3.5.0

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/icons/engagement.svg
    - assets/icons/voice_assistance.svg
    - assets/icons/play.svg
    - assets/icons/pause.svg
    - assets/icons/replay.svg
    - assets/icons/next.svg
    - assets/icons/previous.svg
    - assets/icons/bondtime_logo.svg
    - assets/icons/notifications.svg
    - assets/icons/settings.svg

  fonts:
    - family: InterTight
      fonts:
        - asset: assets/fonts/InterTight-VariableFont_wght.ttf
        - asset: assets/fonts/InterTight-Italic-VariableFont_wght.ttf