name: bondtime
description: A new Flutter project.

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_spinkit: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
#img
  assets:
    - lib/assets/images/father_child.png
    - lib/assets/images/logo.png
    - lib/assets/images/mother_baby.png
    - lib/assets/images/mother_daughter.png
    
