name: baby_profile_app
description: A baby profile UI screen in Flutter.

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.7

flutter:
  uses-material-design: true
  assets:
    - assets/baby.svg