name: bondtime_dashboard
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter

  # UI dependencies
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.10  # For SVG support
  fl_chart: ^0.63.0     # For bar chart graph

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/  # SVG icons (menu & activities)
    - assets/fonts/  # Custom fonts

  fonts:
    - family: InterTight
      fonts:
        - asset: assets/fonts/InterTight-VariableFont_wght.ttf
        - asset: assets/fonts/InterTight-Italic-VariableFont_wght.ttf