name: baby_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.9  # Required for SVG images

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # Add assets (Images & SVGs)
  assets:
    - assets/images/21864181_6502439 1.svg  # Ensure file name is correct
    - assets/fonts/  # Font directory

  # Add custom fonts
  fonts:
    - family: InterTight
      fonts:
        - asset: assets/fonts/InterTight-VariableFont_wght.ttf
        - asset: assets/fonts/InterTight-Italic-VariableFont_wght.ttf
          style: italic
